#!/usr/bin/env python3
"""Regenerates apple/VijfKit/Sources/VijfKit/Tokens.swift from design/tokens.json.

Run from the repo root after changing a colour token:  python3 apple/scripts/generate_tokens.py
TokensTests fails if the Swift file and the JSON disagree.
"""
import json
import pathlib

root = pathlib.Path(__file__).resolve().parents[2]
tokens = json.loads((root / 'design/tokens.json').read_text())['color']['tokens']


def swift_name(name):
    head, *rest = name.split('-')
    return head + ''.join(p.capitalize() for p in rest)


lines = [
    '/// Colour tokens from design/tokens.json (the vijf design system), as hex per theme.',
    '/// Generated by apple/scripts/generate_tokens.py; `TokensTests` fails if this drifts from the JSON.',
    'public enum Tokens {',
    '    public struct Pair: Sendable, Equatable { public let light: String; public let dark: String }',
    '',
]
for t in tokens:
    lines.append(f'    /// {t["usage"]}')
    lines.append(f'    public static let {swift_name(t["name"])} = Pair(light: "{t["value"]["light"]}", dark: "{t["value"]["dark"]}")')
lines += ['', '    /// Every colour by its token name, for the drift test.', '    public static let all: [String: Pair] = [']
lines += [f'        "{t["name"]}": {swift_name(t["name"])},' for t in tokens]
lines += ['    ]', '}']
(root / 'apple/VijfKit/Sources/VijfKit/Tokens.swift').write_text('\n'.join(lines) + '\n')
print(f'Wrote {len(tokens)} colour tokens')
