/// Colour tokens from design/tokens.json (the vijf design system), as hex per theme.
/// Generated by apple/scripts/generate_tokens.py; `TokensTests` fails if this drifts from the JSON.
public enum Tokens {
    public struct Pair: Sendable, Equatable { public let light: String; public let dark: String }

    /// Page background. Text on it: ink, mute.
    public static let paper = Pair(light: "#eae9e5", dark: "#101318")
    /// Raised surfaces: the study card front, box and deck rows, inputs.
    public static let card = Pair(light: "#ffffff", dark: "#1b2028")
    /// Primary text on paper and card; 1.5px borders; fill of primary buttons, box numbers and toasts.
    public static let ink = Pair(light: "#14181f", dark: "#ecece6")
    /// Text and icons on an ink fill (primary button, box number, toast).
    public static let onInk = Pair(light: "#eae9e5", dark: "#14181f")
    /// The action word inside a toast (Undo), on ink.
    public static let onInkAccent = Pair(light: "#ffc917", dark: "#0a3a9e")
    /// Secondary text on paper and card: subtitles, hints, counts of empty boxes, the cog.
    public static let mute = Pair(light: "#65655e", dark: "#9a9a93")
    /// Hairlines and the borders of empty or inactive elements. Never text.
    public static let line = Pair(light: "#c9c9c2", dark: "#343a44")
    /// The yellow of a learned card: the study card's back, the number of a filled box 5.
    public static let signal = Pair(light: "#ffc917", dark: "#ffc917")
    /// Text, border and icon on signal yellow, in both themes.
    public static let onSignal = Pair(light: "#14181f", dark: "#14181f")
    /// Progress ticks, the wordmark's dot, and the focus ring on every surface.
    public static let deep = Pair(light: "#003082", dark: "#7fa6ff")
    /// Fill of the I know it button. Only for that answer.
    public static let success = Pair(light: "#1e7a3c", dark: "#5bd08a")
    /// Text on a success fill.
    public static let onSuccess = Pair(light: "#ffffff", dark: "#14181f")
    /// Fill of Not yet and of swipe-to-delete; text and border of Delete card on paper.
    public static let danger = Pair(light: "#c8102e", dark: "#ff6b75")
    /// Text on a danger fill.
    public static let onDanger = Pair(light: "#ffffff", dark: "#14181f")

    /// Every colour by its token name, for the drift test.
    public static let all: [String: Pair] = [
        "paper": paper,
        "card": card,
        "ink": ink,
        "on-ink": onInk,
        "on-ink-accent": onInkAccent,
        "mute": mute,
        "line": line,
        "signal": signal,
        "on-signal": onSignal,
        "deep": deep,
        "success": success,
        "on-success": onSuccess,
        "danger": danger,
        "on-danger": onDanger,
    ]
}
